version: "3"
services:
  api:
    build: .
    ports:
    - 4000:5000
    environment:
    - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo:4.4
    volumes:
    - simple-crud-db:/data/db

volumes:
  simple-crud-db:
